if GetConvarInt("voice_enableRadioAnim", 1) ~= 0 then
    print("^1PMA-VOICE RADIO ANIMATIONS ENABLED, FOR THIS SCRIPT TO WORK PLEASE ENSURE YOU HAVE THEN DISABLED. Add this to you config or replace it >>> 'setr voice_enableRadioAnim 0'")
    print("^1PMA-VOICE RADIO ANIMATIONS ENABLED, FOR THIS SCRIPT TO WORK PLEASE ENSURE YOU HAVE THEN DISABLED. Add this to you config or replace it >>> 'setr voice_enableRadioAnim 0'")
    print("^1PMA-VOICE RADIO ANIMATIONS ENABLED, FOR THIS SCRIPT TO WORK PLEASE ENSURE YOU HAVE THEN DISABLED. Add this to you config or replace it >>> 'setr voice_enableRadioAnim 0'")
    print("^1PMA-VOICE RADIO ANIMATIONS ENABLED, FOR THIS SCRIPT TO WORK PLEASE ENSURE YOU HAVE THEN DISABLED. Add this to you config or replace it >>> 'setr voice_enableRadioAnim 0'")
    print("^1PMA-VOICE RADIO ANIMATIONS ENABLED, FOR THIS SCRIPT TO WORK PLEASE ENSURE YOU HAVE THEN DISABLED. Add this to you config or replace it >>> 'setr voice_enableRadioAnim 0'")
end

if GetResourceState("rpemotes") == "missing" and GetResourceState("scully_emotemenu") == "missing" then
    print("^1SCULLY_EMOTEMENU OR RPEMOTES IS REQUIRES TO RUN THIS RESOURCE, WITHOUT EITHER OR THE SCRIPT IS USELESS.")
    print("^1SCULLY_EMOTEMENU OR RPEMOTES IS REQUIRES TO RUN THIS RESOURCE, WITHOUT EITHER OR THE SCRIPT IS USELESS.")
    print("^1SCULLY_EMOTEMENU OR RPEMOTES IS REQUIRES TO RUN THIS RESOURCE, WITHOUT EITHER OR THE SCRIPT IS USELESS.")
    print("^1SCULLY_EMOTEMENU OR RPEMOTES IS REQUIRES TO RUN THIS RESOURCE, WITHOUT EITHER OR THE SCRIPT IS USELESS.")
    print("^1SCULLY_EMOTEMENU OR RPEMOTES IS REQUIRES TO RUN THIS RESOURCE, WITHOUT EITHER OR THE SCRIPT IS USELESS.")
end